knpu_oauth2_client:
  clients:
    github:
      type: github
      client_id: "%env(GITHUB_ID)%"
      client_SECRET: "%env(GITHUB_SECRET)%"
      redirect_route: oauth_check
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
