knpu_oauth2_client:
  clients:
    github:
      type: github
      client_id: "%env()%"
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
